# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: worker.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cworker.proto\x12\x06worker\"1\n\nWorkerInfo\x12\n\n\x02id\x18\x01 \x01(\t\x12\x17\n\x0fsupported_model\x18\x02 \x03(\t\")\n\x0bPingRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\"D\n\nJobRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x12\n\nmodel_name\x18\x02 \x01(\t\x12\x12\n\ninput_text\x18\x03 \x01(\t\"c\n\x0bJobResponse\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x11\n\tembedding\x18\x03 \x03(\x02\x12\r\n\x05\x65rror\x18\x04 \x01(\t\x12\x11\n\tworker_id\x18\x05 \x01(\tB=Z;github.com/edgegrid/edgegrid/internal/proto/worker;workerpbb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'worker_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z;github.com/edgegrid/edgegrid/internal/proto/worker;workerpb'
  _WORKERINFO._serialized_start=24
  _WORKERINFO._serialized_end=73
  _PINGREQUEST._serialized_start=75
  _PINGREQUEST._serialized_end=116
  _JOBREQUEST._serialized_start=118
  _JOBREQUEST._serialized_end=186
  _JOBRESPONSE._serialized_start=188
  _JOBRESPONSE._serialized_end=287
# @@protoc_insertion_point(module_scope)
